### ISSUE TITLE
cn-north-1 endpoint doesn't match stream endpoint

### ISSUE THREAD

**Issue by absoludity** [go-amz/amz#21]
The endpoints used in goamz for cn-north-1 [1] use the domain:

amazonaws.com.cn

whereas that published in the stream [2] uses:

amazonaws-cn.com.cn

This means that when bootstrapping (from a non-cn client machine), it fails to find a matching endpoint [3]

That said, as Haw pointed out, the amazonaws.com.cn one from goamz resolves, while the stream one doesn't resolve (from outside .cn) [4], so if it is just the stream being incorrect, this bug is invalid :)

We'd like to try to deploy a staging service to cn-north-1 as soon as we're allowed, but would be blocked on this.

[1] https://github.com/go-amz/amz/blob/v1/aws/aws.go#L145
[2] http://cloud-images.ubuntu.com/releases/streams/v1/index.json
[3] http://paste.ubuntu.com/9890087/
[4] http://paste.ubuntu.com/9890097/

**Comment by axw** [comment]
Looks a lot like the streams data is wrong. I've passed this along to Ben, who can confirm, and CC'd you.

**Comment by darkmuggle** [comment]
Confirmed the data as bad. It'll take a day or two to get this fixed.

**Comment by darkmuggle** [comment]
This is fixed now.

**Comment by axw** [comment]
Thanks!

**Comment by absoludity** [comment]
Thanks for updating the streams. I just tried another bootstrap with the fixed stream data... it still fails though :/ https://pastebin.canonical.com/124380/

**Comment by axw** [comment]
@absoludity Possibly a wrong-side-of-the-GFW problem? I was under the impression that AWS China was restricted to users in China.

**Comment by absoludity** [comment]
@axw I don't think so - that is, yes, AWS China is restricted to users who have a license to operate in China, but that doesn't necessarily mean you can't organise the deployment from an external machine.

What I can check is that I have no problem running, describing and terminating instances in cn-north-1 via the awscli from an external machine [1]. Maybe I should create a separate bug?

[1] https://pastebin.canonical.com/124392/

**Comment by axw** [comment]
@absoludity Thanks for clarifying that. Yes, but I think it probably belongs on the Juju projects.

(BTW, I checked and I can telnet to s3.cn-north-1.amazonaws.com.cn:443. Do you have an HTTP proxy set in your environment?)

**Comment by absoludity** [comment]
@axw Yes, you were right - it was a firewall issue stopping the connection to that URL. I've tried from a different machine where I can access that URL, but the bootstrap fails for a different reason. Created https://github.com/go-amz/amz/issues/22

Thanks.
